# Generated by Django 4.1 on 2023-05-15 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('disciplina', models.TextField(null=True)),
                ('publicada', models.BooleanField(default=False)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
